name: Testing Go Installer

on:
  push:
    branches: [main]
  pull_request:

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Testing
        run: ./test.sh
